# debug2.py

from Engine.UI_Engine_ConsoleX import limpar, enter, input_silencioso, titulo_console, time_s, cursor, escrever_atualizar, escrever, sair, escrever_loading, pular_linha, cursor_posicionar, janela_terminal, anim_loading1, anim_loading2, anim_loading3, status_bar_system_start, status_bar_system, status_bar_system_finish, status_bar_message_start, status_bar_message, status_bar_message_finish, status_bar_log_start, status_bar_log, status_bar_log_finish, texto_rodando, slide_text, anim_box, escrever_piscando, progress_bar

def debug2():
    escrever("testando o limpar...")
    time_s(1)
    limpar()

    escrever("Testando o continuar...")
    time_s(1)
    enter()

    escrever("Testando o input silencioso...")
    test = input_silencioso()
    escrever(f"o que voce escrever foi: {test}!")
    time_s(1)

    escrever("testando as cores...")
    time_s(1)
    escrever("Preto ", "BLACK", "normal", "WHITE")
    time_s(0.3)
    escrever("Vermelho", "RED")
    time_s(0.3)
    escrever("Verde", "GREEN")
    time_s(0.3)
    escrever("Amarelo", "YELLOW")
    time_s(0.3)
    escrever("Azul", "BLUE")
    time_s(0.3)
    escrever("Magenta", "MAGENTA")
    time_s(0.3)
    escrever("Ciano", "CYAN")
    time_s(0.3)
    escrever("Branco", "WHITE")
    time_s(1)

    escrever("Testando fundos...")
    time_s(1)
    escrever("Preto", "WHITE", fundo="BRACK")
    escrever("Vermelho", "WHITE", fundo="RED")
    escrever("Verde", "WHITE", fundo="GREEN")
    escrever("Amarelo", "WHITE", fundo="YELLOW")

    escrever("HORIZON SYSTEM X LOADING...", cor="CYAN", estilo="destaque", velocidade=0.03)
    escrever("Erro crítico detectado!", cor="RED", estilo="destaque", fundo="BLACK", velocidade=0.01)
    escrever("       √•|™[]√√35", "CYAN", "destaque", "BLACK")
    time_s(1)
    
    print("Testando o print original..." )
    time_s(1)
    
    escrever("Testando performance mode...")
    time_s(1)
    escrever("modo performance desligado", performance=None)
    time_s(1)
    escrever("Modo performance ativado!", performance=True)
    time_s(1)
    
    escrever("Olá ", mesma_linha=True, pular_linha=False)
    time_s(1)
    escrever("Mundo!")
    time_s(1)
    
    escrever("Testando o pular_linha...", pular_linha=False)
    time_s(1)
    escrever("deu bom!")
    time_s(1)
    
    escrever("Testando o título da janela do console...")
    time_s(1)
    titulo_console("eai meu mano!")
    time_s(1)
    titulo_console("está funcionando!")
    time_s(1)
    
    escrever("testando o time_s, espere 5 segundos...")
    time_s(5)
    
    cursor(False)
    escrever("Cursor desativado...")
    time_s(1)
    cursor(True)
    escrever("Cursor ativado!")
    time_s(1)

    escrever("Testando o escrever_atulizar...")
    escrever_atualizar("parte atualizada!")
    time_s(1)

    escrever("o sair() pode ser testado assim que voce fechar o debug!")
    time_s(1)

    escrever("Testando o escrever_loading...")
    escrever_loading(5, "aguarde 5 segundos", "GREEN")
    time_s(1)

    escrever("Testando o pular_linha...")
    pular_linha()
    time_s(1)

    escrever("testando o posicionar_cursor... movendo para a linha 2 coluna 3...")
    time_s(1)
    limpar()
    cursor_posicionar(2, 3)
    escrever("Linha 2 - Coluna 3")
    cursor_posicionar(4 ,1)
    time_s(1)

    escrever("Testando a criaçao da janela...")
    time_s(1)
    limpar()
    janela_terminal(2, 2, 28, 6, "debug")
    cursor_posicionar(4, 7)
    cursor(False)
    escrever("Janela funcionando perfeitamente!")
    time_s(2)
    cursor(True)
    cursor_posicionar(1, 1)
    limpar()

    anim_loading1("Testando o anim_loading1")
    escrever("Testando o anim_loading2...")
    anim_loading2(4)
    anim_loading3("Testando o anim_loading3", 4, "RED")

    escrever("Iniciando teste da status_bar.........")
    status_bar_system_start()
    time_s(0.5)
    status_bar_message_start()
    time_s(0.5)
    status_bar_log_start()
    time_s(0.5)
    escrever("Testando status_bar...")
    status_bar_message("Sistema otimo!")
    time_s(0.2)
    status_bar_message("Novas mensagens disponivel...")
    time_s(0.2)
    status_bar_log("Limpeza completa.")
    time_s(2)
    escrever("finalizando as status_bar....")
    status_bar_system_finish()
    status_bar_message_finish()
    status_bar_log_finish()
    limpar()

    escrever("Testando o texto_rolando...")
    texto_rodando("Fala ai, meu mano!")

    escrever("Testando o slide_text...")
    slide_text("-- Olá! --", 10, 0)
    slide_text("-- Olá! --", 0, 10)

    limpar()
    time_s(1)
    limpar()
    anim_box(2, 2, 28, 6)
    cursor_posicionar(4, 7)
    cursor(False)
    escrever("animação da Janela funcionando perfeitamente!")
    time_s(2)
    cursor(True)
    cursor_posicionar(1, 1)
    limpar()

    escrever("testando o escrever_piscando...")
    limpar()
    escrever_piscando("Error", 2, 3, 5)
    limpar()

    escrever("testando a progress_bar...")
    progress_bar()

    escrever("Teste finalizado...")
    time_s(1)
    enter()

# Anderson_Tsunami.11Xx