# list_command.py

# Essa lista contem todos os comandos do sistema para exibir para o usuario.

lista = [
    "ajuda",
    "tempo",
    "versao",
    "reiniciar",
    "hora",
    "data",
    "echo (texto)",
    "desligar",
    "bsod",
    "listar",
    "entrar",
    "local",
    "criar",
    "ler",
    "remover",
    "arquivos",
    "hardware",
    "ram",
    "disco",
    "cpu",
    "vram",
    "rede",
    "processos",
    "config",
    "logs",
    "limpar",
    "info",
    "/kill",
    "dynamic_bar_start",
    "dynamic_bar (messagem)",
    "dynamic_bar_finish",
    "status_bar_system_start",
    "status_bar_system (messagem)",
    "status_bar_system_finish",
    "status_bar_log_start",
    "status_bar_log (messagem)",
    "status_bar_log_finish",
    "status_bar_message_start",
    "status_bar_message (messagem)",
    "status_bar_message_finish",
    "meu_pc",
    "calculadora",
    "assistente",
    "S8E ou s8e",
    "memory_scannet",
    "byte_inspector",
    "pydocs",
    "editor",
    "minerador",
    "navegador",
    "update_system",
    "quebrador_senha",
    "quebrador_numero",
    "createpassword",
    "createpassword2 (senha)",
    "chuva",
    "relogio1",
    "relogio2",
    "relogio3",
    "ghost_clock"
]

# Anderson_Tsunami.M3_E36